### PR TITLE
fix: Invalid cargo crash

### LINKED ISSUE #197: App crashes when getting invalid cargo
The app crashes and I get the following error when the Android Gateway delivers an invalid cargo:

```
2020-09-17 18:43:15.249 13293-13617/tech.relaycorp.courier I/nService$deliverCargo$1: deliverCargo complete
2020-09-17 18:43:15.270 13293-13293/tech.relaycorp.courier W/StoreMessage: Invalid cargo received: Creation date is in the future
2020-09-17 18:43:15.271 13293-13293/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo invalid or malformed cargo 16290826-667a-4c66-9089-16d2d42af4a0
2020-09-17 18:43:15.271 13293-13293/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo closing with error
2020-09-17 18:43:15.285 13293-13293/tech.relaycorp.courier E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.relaycorp.courier, PID: 13293
    java.lang.IllegalStateException: call already closed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:365)
        at tech.relaycorp.cogrpc.server.CogRPCConnectionService$deliverCargo$1$onCompleted$1.invokeSuspend(CogRPCConnectionService.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### PR DESCRIPTION
**Pull request by sdsantos**
Closes #197

I tried for quite some time to get a test to reproduce the issue, but it's tough race condition to reproduce in a test. But reproducing it live was way easier, and this change fixed the race condition.

### CODE REVIEW

**Review by gnarea — CHANGES_REQUESTED** [review]
The issue should be easy to reproduce by creating a cargo with a future creation date as shown in the stack trace in #197 -- try this, for example: https://github.com/relaycorp/relaynet-gateway-android/compare/reproduce-relaynet-courier-android-197

```
10-02 09:50:41.154 6409-6409/tech.relaycorp.courier W/StoreMessage: Invalid cargo received: Creation date is in the future
10-02 09:50:41.155 6409-6409/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo invalid or malformed cargo 420452ce-30c9-4e2b-95ca-239cfe2662e9
10-02 09:50:41.155 6409-6409/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo closing with error
    
    --------- beginning of crash
10-02 09:50:41.174 6409-6409/tech.relaycorp.courier E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.relaycorp.courier, PID: 6409
    java.lang.IllegalStateException: call already closed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:365)
        at tech.relaycorp.cogrpc.server.CogRPCConnectionService$deliverCargo$1$onCompleted$1.invokeSuspend(CogRPCConnectionService.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I'd suggest to write a test that does that here.

**Comment by gnarea** [comment]
Not sure if it makes any difference, but I'm running the courier on Android 5.

**Comment by sdsantos** [comment]
I was able to reproduce it easily with the Gateway app, that's how I know the fix works. But it's due to a race condition that is surprisingly hard to reproduce in a test. After taking too much time trying to write a test for it, I decided to continue just with the fix...

**Review by gnarea — APPROVED** [review]

**Comment by sdsantos** [comment]
> I see. In that case it makes sense, but just to be clear, when you say it's hard to reproduce it in a test do you mean an instrumentation test?

Actually I've tried both, but in theory a unit test should have been enough to reproduce it, since it's a race condition. I was switching coroutines at the wrong moment, making that race condition easier to happen.

**Comment by gnarea** [comment]
Cool, so in that case let's merge it!

**Pull request merged**
