### PR TITLE
chore: CogRPC Server forceful stop

### PR DESCRIPTION
**Pull request by sdsantos**

### CODE REVIEW

**Comment by sdsantos** [comment]
> The code looks good to me, but what would the user experience when the server couldn't be started?

I thought about that, but decided to leave it until I'm implementing the UI and I can get Cláudia's input on it. I was thinking of a simple snackbar (https://material.io/develop/android/components/snackbar/) error message appearing from the bottom.

**Comment by gnarea** [comment]
Makes sense. Can you please make sure that's tracked somewhere (e.g., the Google Doc) so we won't forget about that?

I'll approve this PR once you've resolved the current conflict.

**Comment by sdsantos** [comment]
Just rebased. 

And added a todo to https://github.com/relaycorp/relaynet-courier-android/issues/15 about the error message.

**Comment by gnarea** [comment]
Awesome. Obrigado!

**Pull request merged**
